# DankSearch Configuration
# See https://github.com/AvengeMedia/danksearch for documentation

index_path = "/home/mimame/.cache/danksearch/index"
listen_addr = ":43654"
max_file_bytes = 2097152
worker_count = 6
text_extensions = [
  ".adoc",
  ".asciidoc",
  ".awk",
  ".bib",
  ".c",
  ".cheat",
  ".cl",
  ".clj",
  ".cljs",
  ".conf",
  ".cpp",
  ".cr",
  ".css",
  ".dockerignore",
  ".dot",
  ".edn",
  ".editorconfig",
  ".env",
  ".ex",
  ".exs",
  ".fish",
  ".fnl",
  ".go",
  ".gv",
  ".h",
  ".html",
  ".janet",
  ".java",
  ".jl",
  ".js",
  ".json",
  ".jsx",
  ".kdl",
  ".list",
  ".lua",
  ".md",
  ".mermaid",
  ".nim",
  ".nix",
  ".nu",
  ".php",
  ".proto",
  ".puml",
  ".py",
  ".R",
  ".rb",
  ".rkt",
  ".rs",
  ".scm",
  ".sh",
  ".shards",
  ".sql",
  ".svg",
  ".tex",
  ".theme",
  ".toml",
  ".ts",
  ".tsx",
  ".txt",
  ".typ",
  ".xml",
  ".yaml",
  ".yml",
  ".zig",
]
index_all_files = true
max_depth = 0

[[index_paths]]
path = "/home/mimame"
max_depth = 6
exclude_hidden = true
exclude_dirs = [
  ".cache",
  ".cargo",
  ".composer",
  ".direnv",
  ".eggs",
  ".gem",
  ".git",
  ".gradle",
  ".idea",
  ".m2",
  ".mongodb",
  ".mysql",
  ".next",
  ".npm",
  ".nuxt",
  ".nvm",
  ".parcel-cache",
  ".postgres",
  ".postgresql",
  ".pyenv",
  ".pytest_cache",
  ".rbenv",
  ".redis",
  ".rustup",
  ".serverless",
  ".tox",
  ".Trash-1000",
  ".venv",
  ".vscode",
  ".yarn",
  "__pycache__",
  "bin",
  "bower_components",
  "build",
  "bundle",
  "dist",
  "go",
  "Library",
  "node_modules",
  "obj",
  "out",
  "pg_data",
  "pgdata",
  "result",
  "site-packages",
  "target",
  "vendor",
  "venv",
]
extract_exif = true

[[index_paths]]
path = "/home/mimame/.dotfiles"
max_depth = 6
exclude_hidden = false
exclude_dirs = [
  ".cache",
  ".cargo",
  ".composer",
  ".direnv",
  ".eggs",
  ".gem",
  ".git",
  ".gradle",
  ".idea",
  ".m2",
  ".mongodb",
  ".mysql",
  ".next",
  ".npm",
  ".nuxt",
  ".nvm",
  ".parcel-cache",
  ".postgres",
  ".postgresql",
  ".pyenv",
  ".pytest_cache",
  ".rbenv",
  ".redis",
  ".rustup",
  ".serverless",
  ".tox",
  ".Trash-1000",
  ".venv",
  ".vscode",
  ".yarn",
  "__pycache__",
  "bin",
  "bower_components",
  "build",
  "bundle",
  "dist",
  "go",
  "Library",
  "node_modules",
  "obj",
  "out",
  "pg_data",
  "pgdata",
  "result",
  "site-packages",
  "target",
  "vendor",
  "venv",
]
extract_exif = true
